### PR TITLE
Fixed #84

### LINKED ISSUE #84: Fix hamburger menu
The hamburger menu slips upwards when decreasing screen width. It isn't visible in some mobile screen resolutions in the current deployed version.

### PR DESCRIPTION
**Pull request by Palash3101**
Fixed #84, fixed the hamburger relative to the screen

### CODE REVIEW

**Comment by singh-ab** [comment]
The hamburger menu is visible now in the home page. I personally don't mind it being sticky to the top right like you have done. 
@BlackEyes09  what are your thoughts?

**Comment by singh-ab** [comment]
Also I'll merge this PR but this issue #84 won't be closed until it's fixed on all pages. Do you think you can do it @Palash3101 ? After @BlackEyes09 approves of the sticky feature of hamburger menu of course.

**Comment by Palash3101** [comment]
On the other pages, It by default docks to the top
Do you want me to change that?

**Comment by singh-ab** [comment]
> On the other pages, It by default docks to the top Do you want me to change that?

Part of the issue is that when it locks to the top, it creates it's separate space instead of appearing over the banner.
Screen Shot 2024-12-24 at 14 12 24

Now the UI needs to be consistent across pages. We currently have two options:
1. Locking the menu on top-right of the page.
2. Locking the menu on top-right of the viewport so that it sticks to it. (the feature you are recommending)

Now we need to decide which one to implement. Originally it was supposed to be (1.)
@BlackEyes09 what do you think?

**Comment by BlackEyes09** [comment]
Option 1 is the best in case of design consistency and clean feeling

**Comment by singh-ab** [comment]
> Option 1 is the best in case of design consistency and clean feeling

I think so too. 
@Palash3101 do you think you can do it like option 1? If you need clarifications or help regarding this you can let me know.

**Comment by Palash3101** [comment]
Wilco👍

**Review by singh-ab — CHANGES_REQUESTED** [review]
The logos and buttons are too much in center now. Please change it back to how it was.

Your deployment:
https://aps-iiitdmj-git-fork-palash3101-main-abhays-projects-c75bed56.vercel.app/?_vercel_share=YjlF9ENFX8xEErbV8yssWBFtYiDIsme7

**Comment by Palash3101** [comment]
Screenshot 2024-12-25 160615
 
This ok??

**Comment by singh-ab** [comment]
> Option 1 is the best in case of design consistency and clean feeling

I think so too. 
@Palash3101 do you think you can do it like option 1? If you need clarifications or help regarding this you can let me know.

> Screenshot 2024-12-25 160615
> 
> This ok??

Not quite I think. Although it's hard to compare w/ a screenshot. Compare with the main deployed version.

**Comment by Palash3101** [comment]
It should not have changed much, as the right and left margins have not been tampered with

**Comment by singh-ab** [comment]
It is well aligned now and the hamburger icon is properly aligned too. 
But now in the Home page in mobile mode, the links don't work in the navbar and translucent background doesn't appear.

Screen Shot 2024-12-25 at 21 47 57

**Review by singh-ab — APPROVED** [review]
I've reviewed it and it looks good to go.

**Pull request merged**
